Alias /folkeservice/static/ /var/www/django/folkeservice/static/
<Directory /var/www/django/folkeservice/static/>
  Require all granted
</Directory>
WSGIDaemonProcess folkeservice display-name=folkeservice python-home=/var/www/django/folkeservice/current_venv python-path=/var/www/django/folkeservice/kartplattformen_common
WSGIPassAuthorization On
WSGIProcessGroup folkeservice
WSGIScriptAlias /folkeservice /var/www/django/folkeservice/kartplattformen_common/wsgi.py process-group=folkeservice
<Directory /var/www/django/folkeservice/kartplattformen_common>
  <Files wsgi.py>
    Require all granted
  </Files>
</Directory>